FROM python:3.11-slim
WORKDIR /app

# Copiar e instalar dependencias
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código
COPY backend/ .

# Usar el puerto que asigna Render (variable PORT)
CMD gunicorn app.main:app --bind "0.0.0.0:$PORT"
