FROM python:3.11-slim
WORKDIR /app

# Instalar gunicorn junto con las dependencias
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt gunicorn

COPY backend/ .

CMD gunicorn app.main:app --bind "0.0.0.0:$PORT"
